# backend/app/rebuild/styles/profiles.py

JOURNAL_PROFILES = {
    "management_science": {
        "name": "Management Science",
        "font_name": "Times New Roman",
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "body_columns_num": 1,
        "body_line_spacing": 1.5,
        "title_size": 18,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 11,
        "author_align": "CENTER",
        "abstract_size": 10,
        "abstract_italic": True,
        "abstract_label": "Abstract: ",
        "abstract_indent_in": 0.5,
        "keywords_label": "Keywords: ",
        "heading1_size": 12,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "title",
        "heading1_numbering": "decimal",
        "heading2_size": 11,
        "heading2_bold": True,
        "heading2_italic": True,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "decimal_dot",
        "body_size": 11,
        "body_align": "JUSTIFY",
        "body_first_line_indent_in": 0.5,
        "body_space_after_pt": 6.0,
        "references_size": 10,
        "references_numbering": "none",
        "references_hanging_indent_in": 0.5
    },
    "academy_of_management_journal": {
        "name": "Academy of Management Journal",
        "font_name": "Times New Roman",
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "body_columns_num": 1,
        "body_line_spacing": 2.0,  # Double-spaced
        "title_size": 12,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 12,
        "author_align": "CENTER",
        "abstract_size": 12,
        "abstract_italic": False,
        "abstract_label": "Abstract: ",
        "abstract_indent_in": 0.5,
        "keywords_label": "Keywords: ",
        "heading1_size": 12,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "CENTER",  # Centered bold Level 1 headings
        "heading1_casing": "upper",
        "heading1_numbering": "none",
        "heading2_size": 12,
        "heading2_bold": True,
        "heading2_italic": True,
        "heading2_align": "LEFT",  # Flush left bold italic Level 2 headings
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 12,
        "body_align": "LEFT",
        "body_first_line_indent_in": 0.5,
        "body_space_after_pt": 0.0,
        "references_size": 12,
        "references_numbering": "none",
        "references_hanging_indent_in": 0.5
    },
    "strategic_management_journal": {
        "name": "Strategic Management Journal",
        "font_name": "Times New Roman",
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "body_columns_num": 1,
        "body_line_spacing": 2.0,  # Double-spaced
        "title_size": 14,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 11,
        "author_align": "CENTER",
        "abstract_size": 11,
        "abstract_italic": True,
        "abstract_label": "Abstract: ",
        "abstract_indent_in": 0.5,
        "keywords_label": "Keywords: ",
        "heading1_size": 12,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "title",
        "heading1_numbering": "none",
        "heading2_size": 12,
        "heading2_bold": False,
        "heading2_italic": True,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 11,
        "body_align": "LEFT",
        "body_first_line_indent_in": 0.5,
        "body_space_after_pt": 0.0,
        "references_size": 11,
        "references_numbering": "none",
        "references_hanging_indent_in": 0.5
    },
    "harvard_business_review": {
        "name": "Harvard Business Review",
        "font_name": "Calibri",  # Sans-serif modern magazine look
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.25, "right": 1.25},
        "body_columns_num": 1,
        "body_line_spacing": 1.15,
        "title_size": 22,
        "title_bold": True,
        "title_align": "LEFT",
        "author_size": 11,
        "author_align": "LEFT",
        "abstract_size": 11,
        "abstract_italic": True,
        "abstract_label": "Summary: ",
        "abstract_indent_in": 0.0,
        "keywords_label": "Keywords: ",
        "heading1_size": 14,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "title",
        "heading1_numbering": "none",
        "heading2_size": 12,
        "heading2_bold": True,
        "heading2_italic": True,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 11,
        "body_align": "LEFT",
        "body_first_line_indent_in": 0.0,
        "body_space_after_pt": 8.0,
        "references_size": 10,
        "references_numbering": "none",
        "references_hanging_indent_in": 0.0
    },
    "journal_of_operations_management": {
        "name": "Journal of Operations Management",
        "font_name": "Times New Roman",
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "body_columns_num": 1,
        "body_line_spacing": 2.0,  # Double-spaced
        "title_size": 16,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 11,
        "author_align": "CENTER",
        "abstract_size": 11,
        "abstract_italic": False,
        "abstract_label": "Abstract: ",
        "abstract_indent_in": 0.5,
        "keywords_label": "Keywords: ",
        "heading1_size": 12,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "title",
        "heading1_numbering": "none",
        "heading2_size": 12,
        "heading2_bold": True,
        "heading2_italic": True,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 11,
        "body_align": "LEFT",
        "body_first_line_indent_in": 0.5,
        "body_space_after_pt": 0.0,
        "references_size": 11,
        "references_numbering": "none",
        "references_hanging_indent_in": 0.5
    },
    "mis_quarterly": {
        "name": "MIS Quarterly",
        "font_name": "Times New Roman",
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "body_columns_num": 1,
        "body_line_spacing": 1.5,
        "title_size": 16,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 11,
        "author_align": "CENTER",
        "abstract_size": 10,
        "abstract_italic": True,
        "abstract_label": "Abstract: ",
        "abstract_indent_in": 0.5,
        "keywords_label": "Keywords: ",
        "heading1_size": 12,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "title",
        "heading1_numbering": "none",
        "heading2_size": 11,
        "heading2_bold": True,
        "heading2_italic": True,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 11,
        "body_align": "JUSTIFY",
        "body_first_line_indent_in": 0.5,
        "body_space_after_pt": 6.0,
        "references_size": 10,
        "references_numbering": "none",
        "references_hanging_indent_in": 0.5
    },
    "journal_of_the_acm": {
        "name": "Journal of the ACM",
        "font_name": "Times New Roman",
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "body_columns_num": 1,
        "body_line_spacing": 1.15,
        "title_size": 18,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 11,
        "author_align": "CENTER",
        "abstract_size": 10,
        "abstract_italic": False,
        "abstract_label": "ABSTRACT: ",
        "abstract_indent_in": 0.5,
        "keywords_label": "KEYWORDS: ",
        "heading1_size": 12,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "upper",
        "heading1_numbering": "decimal",
        "heading2_size": 11,
        "heading2_bold": True,
        "heading2_italic": False,
        "heading2_align": "LEFT",
        "heading2_casing": "title",
        "heading2_numbering": "decimal_dot",
        "body_size": 10,
        "body_align": "JUSTIFY",
        "body_first_line_indent_in": 0.25,
        "body_space_after_pt": 6.0,
        "references_size": 9,
        "references_numbering": "brackets",
        "references_hanging_indent_in": 0.2
    },
    "nature_machine_intelligence": {
        "name": "Nature Machine Intelligence",
        "font_name": "Arial",  # Nature Journals use Arial
        "margins_in": {"top": 0.75, "bottom": 0.75, "left": 0.75, "right": 0.75},
        "body_columns_num": 2,
        "body_columns_gap_in": 0.25,
        "body_line_spacing": 1.0,
        "title_size": 18,
        "title_bold": True,
        "title_align": "LEFT",
        "author_size": 10,
        "author_align": "LEFT",
        "abstract_size": 9,
        "abstract_italic": False,
        "abstract_label": "",
        "abstract_indent_in": 0.0,
        "keywords_label": "",
        "heading1_size": 10,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "none",
        "heading1_numbering": "none",
        "heading2_size": 9,
        "heading2_bold": True,
        "heading2_italic": False,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 9,
        "body_align": "JUSTIFY",
        "body_first_line_indent_in": 0.12,
        "body_space_after_pt": 4.0,
        "references_size": 8,
        "references_numbering": "number_dot",
        "references_hanging_indent_in": 0.15
    },
    "information_management": {
        "name": "Information & Management",
        "font_name": "Times New Roman",
        "margins_in": {"top": 1.0, "bottom": 1.0, "left": 1.0, "right": 1.0},
        "body_columns_num": 1,
        "body_line_spacing": 1.15,
        "title_size": 18,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 11,
        "author_align": "CENTER",
        "abstract_size": 10,
        "abstract_italic": False,
        "abstract_label": "Abstract: ",
        "abstract_indent_in": 0.5,
        "keywords_label": "Keywords: ",
        "heading1_size": 12,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "title",
        "heading1_numbering": "decimal",
        "heading2_size": 11,
        "heading2_bold": True,
        "heading2_italic": False,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "decimal_dot",
        "body_size": 11,
        "body_align": "JUSTIFY",
        "body_first_line_indent_in": 0.25,
        "body_space_after_pt": 6.0,
        "references_size": 9,
        "references_numbering": "brackets",
        "references_hanging_indent_in": 0.2
    },
    "nature": {
        "name": "Nature",
        "font_name": "Arial",
        "margins_in": {"top": 0.75, "bottom": 0.75, "left": 0.75, "right": 0.75},
        "body_columns_num": 2,
        "body_columns_gap_in": 0.25,
        "body_line_spacing": 1.0,
        "title_size": 20,
        "title_bold": True,
        "title_align": "LEFT",
        "author_size": 10,
        "author_align": "LEFT",
        "abstract_size": 9,
        "abstract_italic": False,
        "abstract_label": "",
        "abstract_indent_in": 0.0,
        "keywords_label": "",
        "heading1_size": 10,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "none",
        "heading1_numbering": "none",
        "heading2_size": 9,
        "heading2_bold": True,
        "heading2_italic": False,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 9,
        "body_align": "JUSTIFY",
        "body_first_line_indent_in": 0.12,
        "body_space_after_pt": 4.0,
        "references_size": 8,
        "references_numbering": "number_dot",
        "references_hanging_indent_in": 0.15
    },
    "science": {
        "name": "Science",
        "font_name": "Times New Roman",
        "margins_in": {"top": 0.75, "bottom": 0.75, "left": 0.75, "right": 0.75},
        "body_columns_num": 2,
        "body_columns_gap_in": 0.25,
        "body_line_spacing": 1.0,
        "title_size": 20,
        "title_bold": True,
        "title_align": "CENTER",
        "author_size": 10,
        "author_align": "CENTER",
        "abstract_size": 9,
        "abstract_italic": False,
        "abstract_label": "",
        "abstract_indent_in": 0.0,
        "keywords_label": "",
        "heading1_size": 10,
        "heading1_bold": True,
        "heading1_italic": False,
        "heading1_align": "LEFT",
        "heading1_casing": "none",
        "heading1_numbering": "none",
        "heading2_size": 9,
        "heading2_bold": True,
        "heading2_italic": False,
        "heading2_align": "LEFT",
        "heading2_casing": "none",
        "heading2_numbering": "none",
        "body_size": 9,
        "body_align": "JUSTIFY",
        "body_first_line_indent_in": 0.12,
        "body_space_after_pt": 4.0,
        "references_size": 8,
        "references_numbering": "number_dot",
        "references_hanging_indent_in": 0.15
    }
}
